name: Golang-try
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
         go-version: '>=1.17.0'
      - run: go mod tidy
      - run: go install gioui.org/cmd/gogio@latest
      - run: gogio -target js random.msg
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Translate to wasm
          branch: frontend/wasm
          create_branch: true
